version: '3.9'
services:
  mongodb:
    image: mongo:4.4.5
    ports:
    - "27017:27017"
    labels:
      type: db # container
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=password
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 10s # between restart attempts
      labels:
        tier: backend # service
      resources:
        limits:
          cpus: '0.5'
          memory: 200M

  mongo-express:
    image: mongo-express:0.54
    ports:
    - "8081:8081"
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    - ME_CONFIG_MONGODB_SERVER=mongodb
  